stages:
  - build
  - test

# Простейший build job
build_job:
  stage: build
  script:
    - echo "Build stage: Runner работает!"
    - echo "Текущая директория: $(pwd)"
    - ls -la

# Простейший test job
test_job:
  stage: test
  script:
    - echo "Test stage: Runner тоже работает!"
