stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: my-django-app:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    # Остановим старый контейнер (если есть)
    - docker rm -f django-app || true
    # Запустим новый контейнер
    - docker run -d --name django-app -p 8000:8000 $DOCKER_IMAGE
  only:
    - main
