stages:
  - build
  - test
  - deploy

# Сборка Docker-образа
build:
  stage: build
  image: docker:latest
  script:
    - ls -l /var/run/docker.sock
    - docker info
    - docker build -t my-app:latest .


test:
  stage: test
  image: docker:latest
  script:
    # Пример: запускаем контейнер и проверяем, что он стартует
    - docker run -d --name test-app -p 5000:5000 my-app:latest
    - sleep 5
    - docker ps | grep test-app
    # Здесь можно добавить pytest, curl http://localhost:5000 и т.д.
    - docker stop test-app && docker rm test-app

# Деплой на сервер (локально)
deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker stop my-app || true
    - docker rm my-app || true
    - docker run -d --name my-app -p 8080:80 my-app:latest
  only:
    - main
